spring:
  datasource:
    url: jdbc:mysql://localhost:3306/GooGooDb?serverTimezone=UTC
    username: user
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    user:
      name: admin
      password: admin123
server:
  port: 8081
  url: http://localhost:8081 # 이 줄을 추가하세요.

# JWT 설정 추가
jwt:
  secret: 'yK3V6y4G8J9LdQ0rS3V6yG9J0kL2mN5pQ8sR5vT8wX1zA4b7C6d9E0f3sdfsdrsdfsdfsdfsdfH4i6J7kLhuiokjhsdfuisdjfhsd' # Base64URL 인코딩된 예시
  expiration:
    ms: 10800000 # 3시간 (밀리초 단위)

file:
  upload-dir: ./uploads